### ISSUE TITLE
cannot import name 'QuantizedCacheConfig' from 'transformers.cache_utils' [FIX]

### ISSUE THREAD

**Issue by rzgarespo** [billwuhao/ComfyUI_IndexTTS#48]
_My ComfyUI transformers version is 4.56.1._
`pip install json5 munch`

**Replace the codes in text files with the current code. [ Pay attention to the current date and the node's version to ensure that the patches haven't already been applied. ]**

[transformers_gp2.txt](https://github.com/user-attachments/files/22408203/transformers_gp2.txt)
[transformers_generation_utils.txt](https://github.com/user-attachments/files/22408202/transformers_generation_utils.txt)

```
cd ComfyUI directory/models/TTS
git lfs install
git clone https://huggingface.co/IndexTeam/IndexTTS-2

```

Full log:
1. Files Modified:
----------------
a)  /ComfyUI/custom_nodes/indextts-mw/indextts/gpt/transformers_generation_utils.py
   - Removed QuantizedCacheConfig import
   - Added custom _crop_past_key_values implementation
   - Added custom NEED_SETUP_CACHE_CLASSES_MAPPING
   - Modified cache implementation logic

b) /ComfyUI/custom_nodes/indextts-mw/indextts/gpt/transformers_gpt2.py
   - Added custom SequenceSummary implementation
   - Removed duplicate SequenceSummary class
   - Fixed import structure
   - Modified imports to work with transformers 4.56.1

2. Packages Installed:
--------------------
1. json5 (version 0.9.25)
   - Required by: indextts.utils.maskgct_utils
   - Installation method: conda install -n comfy json5
   - Purpose: JSON5 parsing capabilities

2. munch (version 2.5.0)
   - Required by: indextts.s2mel.modules.commons
   - Installation method: conda install -n comfy munch
   - Purpose: Creating Python dictionaries with attribute-style access

3. Environment Details:
---------------------
- Python Environment: Conda (env name: comfy)
- Transformers version: 4.56.1
- Platform: Linux

4. Code Compatibility Changes:
---------------------------
1. Transformers API Compatibility:
   - Removed dependencies on QuantizedCacheConfig (not available in 4.56.1)
   - Implemented local version of SequenceSummary class
   - Modified cache implementation to use standard DynamicCache

2. Cache Implementation:
   - Added simplified cache mapping:
     ```python
     NEED_SETUP_CACHE_CLASSES_MAPPING = {
         "dynamic": DynamicCache,
         "static": StaticCache,
     }
     ```

Notes:
- All modifications are made to maintain compatibility with transformers 4.56.1
- Original functionality is preserved using local implementations where needed
- Cache system simplified to use standard dynamic and static caches

**Comment by radzhang** [comment]
Thank you!

**Comment by lucasye2008** [comment]
Thanks a lot

**Comment by liujintiger** [comment]
There is a file naming error above. Changing "transformers_gp2.txt" to "transformers_gpt2.py" will prevent the error "No module named 'indextts.gpt.transformers_gpt2'".
